# docker compose -f compose-infra.yml up -d

services:
  mongodb:
    image: mongo:7.0
    container_name: mongodb7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: elysiajs
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - elysia-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongodb_data:

networks:
  elysia-network:
    driver: bridge
